batch_size: 64
epochs: 200
eval_every_n_epochs: 1
fine_tune_from: 'scratch'
trained_with: 'CGCNN'
log_every_n_steps: 50
gpu: cuda:0
vocab_path: 'tokenizer/vocab_full.txt'
cuda: True
num_workers: 0
task: 'regression'

optim:
  optimizer: Adam
  init_lr: 0.00005
  weight_decay: 1e-6


dataloader:
  valid_ratio: 0.15
  test_ratio: 0.15
  use_ratio: 1
  randomSeed: 1

target_property: Di

dataset:
  data_name: CoRE2019
  dataPath: ./test_datasets/mofid_{target_property}.csv

Transformer:
  ntoken: 4021
  d_model: 512
  nhead: 8
  d_hid: 512
  nlayers: 6
  dropout: 0.1